### PR TITLE
fix: installation on Node 7 and below

### LINKED ISSUE #219: 2.0.1 installation error
I don't get this when I reinstall 2.0.0, but on 2.0.1:

```
19:34 $ npm i --save-dev ghooks@2.0.1
macaron http request GET https://registry.npmjs.org/ghooks
macaron http 304 https://registry.npmjs.org/ghooks
macaron http request GET https://registry.npmjs.org/findup
macaron http request GET https://registry.npmjs.org/lodash.clone
macaron http request GET https://registry.npmjs.org/manage-path
macaron http request GET https://registry.npmjs.org/opt-cli
macaron http request GET https://registry.npmjs.org/spawn-command
macaron http request GET https://registry.npmjs.org/path-exists
macaron http 304 https://registry.npmjs.org/findup
macaron http 304 https://registry.npmjs.org/path-exists
macaron http 304 https://registry.npmjs.org/lodash.clone
macaron http 304 https://registry.npmjs.org/spawn-command
macaron http 304 https://registry.npmjs.org/opt-cli
macaron http 304 https://registry.npmjs.org/manage-path
macaron http request GET https://registry.npmjs.org/colors
macaron http request GET https://registry.npmjs.org/commander
macaron http 304 https://registry.npmjs.org/colors
macaron http 304 https://registry.npmjs.org/commander

> ghooks@2.0.1 install /Users/ronkorving/Projects/macaron/node_modules/ghooks
> node ./bin/module-install


ghooks postinstall could not be completed.
==========================================

Usually this is due to using npm@2.15.x. Please consider updating npm
to its latest version or run the following command manually afterwards:

	npm explore ghooks -- npm run install

See https://github.com/gtramontina/ghooks/issues/71 for more information.

- cross-spawn-async@2.2.5 node_modules/cross-spawn-async
- path-key@1.0.0 node_modules/path-key
- npm-run-path@1.0.0 node_modules/npm-run-path
- execa@0.4.0 node_modules/execa
macaron@1.22.0 /Users/ronkorving/Projects/macaron
└─┬ ghooks@2.0.1 
  ├── lodash.clone@4.5.0 
  ├─┬ opt-cli@1.5.1
  │ └── lodash.clone@4.3.2 
  └── path-exists@3.0.0 
```

NPM version is 4.2.0 on Node 7.10.0

### PR DESCRIPTION
**Pull request by ta2edchimp**
Fixes #219

### CODE REVIEW

**Comment by ronkorving** [comment]
And why was this not a problem on Travis, I wonder?

**Comment by gtramontina** [comment]
Yeah, that got me thinking as well. `¬_¬`

**Comment by ronkorving** [comment]
Confirmed in my environment, 2.0.2 works 👍

**Comment by ta2edchimp** [comment]
Yeah, I expected the CI builds to fail, as we have ghooks itself added as a dependency (semver "*"), and it in fact did fail locally on Node 7 and below because of running the affected ghooks 2.0.1 upon `npm install`. I even started further steps to get around it. To be honest, I was just happy it did not fail on CI eventually and so I did not investigate further.

**Pull request merged**
