### PR TITLE
build: ditch transpilation

### PR DESCRIPTION
**Pull request by gtramontina**
Addresses #217.

### CODE REVIEW

**Comment by gtramontina** [comment]
👍 for moving install into `bin`. I think we can do this as a separate step (separate PR), as my initial intent with this one was to unblock https://github.com/ghooks-org/ghooks/pull/216.

Running `npm run semantic-release` locally, executes a dry-run. It gave me this back:

```
semantic-release WARN pre semantic-release didn’t run on Travis CI and therefore a new version won’t be published.
semantic-release WARN pre You can customize this behavior using "verifyConditions" plugins: git.io/sr-plugins
semantic-release ERR! pre Determined version 2.0.1 as "latest". Not publishing in debug mode. { type: 'patch', version: '2.0.1' }
```
Which apparently is correct (patch release: `2.0.1`), or were you suggesting that there should be no  release with these changes…?

**Comment by ta2edchimp** [comment]
I would interpret it as a breaking change to not support Node prior to v4 anymore (regardless of the reason behind), so I'm definitely against it being only a patch release.  
So, _if_ making a release, I think it should be a major version bump. And then we should make it properly, that is, removing the deprecation notice / update the readme and also move install to `bin`.

**Comment by gtramontina** [comment]
Oh yeah, definitely! Quit supporting node 4 is definitely a breaking change. I did think these changes would break compatibility, however everything is still fine with node 4 and above:
* [travis](https://travis-ci.org/ghooks-org/ghooks/builds/305174565)
* [appveyor](https://ci.appveyor.com/project/gtramontina/ghooks/build/1.0.13)

Apparently we were only using babel for deconstructing a few requires, which I addressed like the following:

```diff
-const {resolve, basename} = require('path')
+const resolve = require('path').resolve
+const basename = require('path').basename
```

* `lib/runner.js` https://github.com/ghooks-org/ghooks/pull/218/files#diff-b3b53682a18f203ac8d29b0e277cad26L1
* `lib/hook.template.js`: https://github.com/ghooks-org/ghooks/pull/218/files#diff-84b93692b669eac624176e385c8ab3e9L2

**Comment by ta2edchimp** [comment]
So if it _is_ a [breaking change, it should be a major release](https://www.npmjs.com/package/semantic-release#major-breaking-release) then, shouldn't it?  
And then, the deprecation status should be removed prior to releasing.

(Sorry for being so nitpicking 🙈)

**Comment by gtramontina** [comment]
No need to apologize! We're just trying to get on the same page… 😉

I do agree that if it is a breaking change, it should be a major release (as a general rule). Although that is not the case with the changes on this PR in particular. We didn't break compatibility with node 4.

Initially, I _though_ we would have to stop supporting node 4, but it turns out it was very straightforward to remove babel from the game and keep the code compatible with node 4.

So, unless I'm not seeing something, we're good to tag these changes as patch… (?)

**Comment by ta2edchimp** [comment]
Let‘s do it :+1:

Nevertheless, update the Readme / unmark as deprecated  prior to releasing? Or do we wait until the first feature release?

**Comment by gtramontina** [comment]
Cool. Does that make sense? I feel like there's something iffy… (interpreting people's reaction from textual comms is hard) 😄

I guess we can do it as soon as a new `2.0.1` is out.

**Comment by ta2edchimp** [comment]
It’s all good. I‘m not a native english speaker, so things might sound different as intended.

I only worried about the package’s readme over at npmjs which will be the version at the time of publishing the release (that is, it might lead to reactions like „why releasing an update when it’s deprecated?“).  
But I guess it’s a non-issue, since we want to get some more releases out soon.

So, from my end, let‘s go 🙂

**Comment by gtramontina** [comment]
I get you now… Over at npm it'll still read as deprecated. That's indeed a valid concern! How about this, then: I'll remove the deprecation note from the readme, add it as part of this PR and then we merge and call it `2.0.1`.

ps: I'm not native english speaker either 😃

**Comment by ta2edchimp** [comment]
Awesome!

**Pull request merged**
